### ISSUE TITLE
Error when starting google_assistant.py

### ISSUE THREAD

**Issue by Marsupilami23** [respeaker/mic_hat#1]
I'm getting an error when starting google_assistant.py:

`Traceback (most recent call last):
  File "mic_hat/google_assistant.py", line 24, in <module>
    import google.oauth2.credentials
ImportError: No module named google.oauth2.credentials`

Starting google-assistant-demo normally is fine.

**Comment by jerryyip** [comment]
have you activated the virtual env?

**Comment by Marsupilami23** [comment]
I just realized what I did wrong as I posted this. Had to install as env environment.

Thanks! Working now.

**Comment by jerryyip** [comment]
OK, I will close this issue.
