### ISSUE TITLE
Note on Google Assistant Library compatibility with arm6 devices.

### ISSUE THREAD

**Issue by giano** [respeaker/mic_hat#4]
Not an issue "per se" but should be noted that actual python version of Google Assistant Library is not compatible with arm6 devices (Raspberry Pi Zero, Raspberry Pi Zero W, Raspberry Pi 2 and older models).

It requires arm7 instructions.

**Comment by gerardwr** [comment]
The Google Assistant example “pushtotalk” works OK on RPi Zero, but this is without the recognition of “ok Google” hotword.

The installation procedure was temporarily broken but it was fixed yesterday:
https://github.com/googlesamples/assistant-sdk-python/issues/235

But the hotword example seems to use Arm7 instructions for the hotword recognition, So this does not work on the Zero.

**Comment by AIWintermuteAI** [comment]
Since that time Google depreciated Google Assistant Library and switched to Google Assistant Service instead, which DOES NOT have Keyword detection capability.
We plan to use opensource Mycroft Precise for the keyword detection in upgraded demo.
Closing the issue.
