### ISSUE TITLE
Thanks ! Is working with Google Assistant GassistPi

### ISSUE THREAD

**Issue by Pnether** [respeaker/mic_hat#5]
Thanks! I used and shared your pixels script for the Google Assistant project GassistPi [https://github.com/shivasiddharth/GassistPi](url) to light up the built-on LEDs of Respeaker 2-mic.
I used the pixels.think() and pixel.speak() commands, and it looks great !

**Comment by AIWintermuteAI** [comment]
Excellent! Glad that it worked!
Closing the issue.
