### ISSUE TITLE
ReSpeaker 2-mic leds unexpected in listening mode

### ISSUE THREAD

**Issue by gerardwr** [respeaker/mic_hat#7]
The Google-Assistant code in this Github works nicely, including the leds.

The only issue is that often the leds suddenly light up in listening mode, without Google Assistant is in actieve mode. It continuous lights up untill the “ok Google” is spoken again.

Could  it be a false recognition of “ok Google”, and the leds are not switched off when a followup phrase is not received?

**Comment by gerardwr** [comment]
Did some more testing.

When you speak "ok google" without a followup phrase the leds start blinking in listening mode indefinitely.

Speaking "ok google stop" or "ok google" with a followup phrase resets the leds, and the work again expected.

So i guess this a bug in the code.

**Comment by gerardwr** [comment]
I added some code in google-asssitant.py to switch the leds off in case of an ON_CONVERSATION_TURN_TIMEOUT event. Now the leds are switched off when "ok google" is not followed by a followup phrase.

```
    if event.type == EventType.ON_RESPONDING_STARTED:
        pixels.speak()

    if event.type == EventType.ON_CONVERSATION_TURN_TIMEOUT:
        pixels.off()

    if event.type == EventType.ON_CONVERSATION_TURN_FINISHED:
        if event.args and event.args['with_follow_on_turn']:
            pixels.listen()
        else:
            pixels.off()
            print()
```

**Comment by AIWintermuteAI** [comment]
Excellent!
I'll keep that in mind when upgrading google-assistant example.
Closing the issue.
